import React from "react"
import { Tab } from "./Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/Ki6ZyS01gy2W46wkWXZ5do/Simple-Design-System--Community?node-id=3729%3A12963",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover"
      // }),
      // "active": figma.boolean('Active')
    },
    example: (props) => <Tab />,
  },
)
