import React from "react"
import { Button } from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/Ki6ZyS01gy2W46wkWXZ5do/Simple-Design-System--Community-?node-id=4185-3778",
  {
    props: {
      label: figma.string("Label"),
      iconEnd: figma.instance("Icon End"),
      hasIconEnd: figma.boolean("Has Icon End"),
      hasIconStart: figma.boolean("Has Icon Start"),
      iconStart: figma.instance("Icon Start"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      state: figma.enum("State", {
        Default: "default",
        Hover: "hover",
        Disabled: "disabled",
      }),
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
    },
    example: () => <Button />,
  },
)
